# Generated by Django 3.1.4 on 2021-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='justification',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
